### ISSUE TITLE
feature: input field for custom class

### ISSUE THREAD

**Issue by mrkbr** [einpraegsam/typoscript2ce#10]
Hi Alex, 
thanks for this useful extension. 

I use it for example to load content of subpages onto the main page of a one pager. This cleans up things and customers can edit content on pages what makes it clean.

One thing i am missing is the option to wrap those contents with a custom wrapper. If you would add a field to enter a custom class this would be even more versatile. The best would be to offer this as override field - if you enter a class it will remove "tx-typoscript2ce" and add a new class.

Cheers and best wishes,
Mario

**Comment by einpraegsam** [comment]
Hi Mario,

sorry but I don't want to extend this extension any more, because the complete extension is not useful. Why: This is simply a ViewHelper that already exists. If I would need to render TypoScript as a content element I would simply extend my sitepackage with this very small functionality.

So you (and everyone else) could ask: "So, why is this extension existing?". The answer is simple: I once did not know how simple things can be and I added this extension to TER. Now some people are still using this extension and I don't want to delete it.
It does not need so much time to update this extension from TYPO3 version to version, because it is so simple. I don't want to make it more complicate :)

In your case: You could change the template to your needs if you want.

Hope you understand my position, Alex

**Comment by Patta** [comment]
@mrkbr you could e.g. load the page title or ID as class in the fluid layout of typoscript2ce from a variable.
